name: Deploy

on:
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy para hostinger
        uses: easingthemes/ssh-deploy@main
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          TARGET: app


  build:
    name: Build
    runs-on: ubuntu-latest
    needs: continuos-integration
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd app
          ls -la
          npm install
          npm run start
          
    
    

            



