on:
  push:
    branches:
      - main
name: Deploy from Farmnext
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-lastest
    steps:
    - name: Pegando codigo mais recente....
      uses: actions/checkout@v2
    - name:  📁 Colocando arquivos no servidor
      uses: cross-the-world/ssh-pipeline@master
      env:
        WELCOME: "ssh pipeline"
      with:
        host: '145.223.29.160'
        user: root
        pass: ${{ secrets.SERVER_PASSWORD}}
        port: 22
        connect_timeout: 10s
        script: |
          git clone git@github.com:gabrielbwitte/farmnext.git
          
          
    

      
