name: Deploy

on:
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo Building the app
  
  deploy-development:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://github.com/gabrielbwitte/farmnext.git
    needs: build
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v1
      - name: Hostinger Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{secrets.SERVER_IP}}
          REMOTE_USER: ${{secrets.SERVER_USER}}
          REMOTE_PORT: ${{secrets.SERVER_PORT}}
          TARGET: |
            npm install
            npm run start

            



